const SIGNUP_PENDING = "SIGNUP_PENDING";
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
const SIGNUP_ERROR = "SIGNUP_ERROR";
const GET_COUNTRIES_PENDING = "GET_COUNTRIES_PENDING";
const GET_COUNTRIES_SUCCESS = "GET_COUNTRIES_SUCCESS";
const GET_COUNTRIES_ERROR = "GET_COUNTRIES_ERROR";

export { SIGNUP_PENDING, SIGNUP_SUCCESS, SIGNUP_ERROR, GET_COUNTRIES_PENDING, GET_COUNTRIES_SUCCESS, GET_COUNTRIES_ERROR };
